### ISSUE TITLE
Query regarding the container

### ISSUE THREAD

**Issue by vivekanand1101** [DxCx/docker-astrobox#1]
Hi,

Is it that Astrobox can't be installed on ubuntu or any other os? I myself use fedora and thought a docker container might be of help. If so, what changes might be required (if in case you know)?

**Comment by DxCx** [comment]
hey @vivekanand1101 i worked on that more then a year ago so i cant really remember,
but looking at the Dockerfile
https://github.com/DxCx/docker-astrobox/blob/master/Dockerfile
looks like i did build it over ubuntu and there are the steps there.
hope it helps.

**Comment by vivekanand1101** [comment]
Thank you @DxCx  , i will see what i can do with it :)
